# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new build to Google Play"
  lane :publish do
    gradle(task: "clean")
    gradle(
      task: "bundle", # use "assemble" to build an .apk instead
      build_type: "Release",
      properties: {
	"android.injected.signing.store.file" => ENV["TONUINO_KEYSTORE"],
        "android.injected.signing.store.password" => ENV["TONUINO_KEYSTORE_PASS"],
        "android.injected.signing.key.password" => ENV["TONUINO_KEY_PASS"],
        "android.injected.signing.key.alias" => ENV["TONUINO_KEY"],
      }
    )
    upload_to_play_store(
      track: ENV["PLAY_STORE_TRACK"],
      skip_upload_screenshots: true,
    )
  end
end
