# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
      task: "clean assembleRelease",
      properties: {
        "android.injected.signing.store.file" => ENV["HOME"] + "/android/keystore.jks",
        "android.injected.signing.store.password" => ENV["TONUINO_KEYSTORE_PASSWORD"],

        "android.injected.signing.key.password" => ENV["TONUINO_KEY_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["TONUINO_KEY"],
      }
    )
    upload_to_play_store(
      track: 'beta',
      skip_upload_screenshots: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
